### ISSUE TITLE
Images not loading on the home page

### ISSUE THREAD

**Issue by ianmurchison** [ngrealish/myfpv-issues#16]
macOS - Safari

Not seeing any images on the homepage

<img width="1479" alt="image" src="https://user-images.githubusercontent.com/26898748/71646989-92b50780-2cbd-11ea-92e0-3475e2a3025a.png">

**Comment by ngrealish** [comment]
Thank you for adding this issue! I'll take a look tonight just after dinner. Thank you again!

**Comment by ngrealish** [comment]
I believe this issue has been fixed.  This was a CSS issue where the image element was not receiving the height of its parent.  Not sure why, but I put a bit of css trickery in there for safari for it to work properly.  Images should be working in production in less than 2 minutes . 

Please feel free to re-open if you're still seeing an issue (remember to clear cache first)
