### ISSUE TITLE
Login button is not super obvious

### ISSUE THREAD

**Issue by AlexRoberts** [ngrealish/myfpv-issues#18]
Probably because I'm not super well-versed in iconography, but a simple sign-in / sign up button might be nice.

![image](https://user-images.githubusercontent.com/4239390/71675348-92fbe400-2d4b-11ea-8c4c-1f32a8531fb7.png)

**Comment by ngrealish** [comment]
Thank you! I've started to label icons recently, so I may be able to turn this into a labeled button, rather than just an icon. I'll get on this.
